version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=password
    networks:
      - wp

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes: ["./html:/var/www/html"]
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
    networks:
    - wp

networks:
  wp:
volumes:
  db_data: